### ISSUE TITLE
Скролл модального окна с формой

### ISSUE THREAD

**Issue by useyourillusions** [DashaBaltsevich/FOINI-REACT-SS#3]
Нельзя проскроллить модальное окно, когда недостаточно места по вертикали для его полного отображения

<img width="724" alt="image" src="https://user-images.githubusercontent.com/17027437/161693344-48c230d4-52e7-455e-a0c2-ca568c4d39b1.png">

**Comment by DashaBaltsevich** [comment]
Все должно работать уже.

**Comment by useyourillusions** [comment]
> Все должно работать уже.
